// entry/src/main/ets/data/IslamicEvents.ets

import { IslamicEvent } from '../models/DateModels';

export const IMPORTANT_ISLAMIC_EVENTS: IslamicEvent[] = [
  { name: 'Islamic New Year', month: 1, day: 1 },
  { name: 'Day of Ashura', month: 1, day: 10 },
  { name: 'Mawlid al-Nabi', month: 3, day: 12 },
  { name: 'Isra and Mi\'raj', month: 7, day: 27 },
  { name: 'Mid-Sha\'ban', month: 8, day: 15 },
  { name: 'Ramadan Start', month: 9, day: 1 },
  { name: 'Eid al-Fitr', month: 10, day: 1 },
  { name: 'Day of Arafah', month: 12, day: 9 },
  { name: 'Eid al-Adha', month: 12, day: 10 }
];