// entry/src/main/ets/common/StorageKeys.ets

export const STORAGE_KEY_CALC_METHOD = 'prayer_calc_method';
export const STORAGE_KEY_ASR_RULE = 'prayer_asr_rule';
export const STORAGE_KEY_CALC_SOURCE = 'prayer_calc_source';
export const STORAGE_KEY_COUNTER = 'prayer_counter';

export const STORAGE_KEY_CACHED_LAT = 'cached_latitude';
export const STORAGE_KEY_CACHED_LNG = 'cached_longitude';
export const STORAGE_KEY_CACHED_CITY = 'cached_city';